POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "author": "The title or url is missing"
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "author": "John Doe",
  "title": "Example Domain",
  "url": "https://example.com/",
  "likes": 17
}

###
GET http://localhost:3003/api/blogs

###
PUT http://localhost:3003/api/blogs/658162fe01b40b8265d92b1a HTTP/1.1
content-type: application/json

{
  "title": "Example Domain",
  "author": "Jane Doe",
  "url": "https://example.com/",
  "likes": 8,
  "id": "658162fe01b40b8265d92b1a"
}