POST http://localhost:3003/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "The name, author or url is missing"
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "name": "John Doe",
  "title": "HTTP magic",
  "url": "www.imgur.com/a/G6rU8",
  "likes": 17
}
