POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "author": "The title or url is missing"
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "author": "John Doe",
  "title": "Example Domain",
  "url": "https://example.com/",
  "likes": 17
}
