POST http://localhost:3003/api/users/ HTTP/1.1
Content-Type: application/json

{
  "username": "JohnDoe",
  "password": "Doe",
  "name": "John Doe"
}
###
POST http://localhost:3003/api/users/ HTTP/1.1
Content-Type: application/json

{
  "username": "JohnDoe",
  "password": "JD",
  "name": "Short password: 400 Error"
}

###
POST http://localhost:3003/api/users/ HTTP/1.1
Content-Type: application/json

{
  "username": "JD",
  "password": "John",
  "name": "Short username: 400 Error"
}

###
GET http://localhost:3003/api/users

###
PUT http://localhost:3003/api/users/6589c46fb43ffdeb2a632ca2 HTTP/1.1
Content-Type: application/json

{
  "username": "JaneDoe",
  "password": "Doe",
  "name": "Jane Doe",
  "id": "6589c46fb43ffdeb2a632ca2"
}